eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762
  
spring:
  application:
    name: zuul-server
    
management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

