version: '3'

services:
  quarkus-build:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      - mongo-express
      - mongo
    environment:
      DB_MONGO: mongodb://mongo:27017
      URL_JAEGER: http://jaeger:14268/api/traces
    ports:
      - "8080:8080"
    networks:
      - mongo-compose-network
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGODB_DATABASE: desafio
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - mongo-compose-network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: '"true"'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: desafio
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge